In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [6]:
df=pd.read_csv("fifa19 (1).csv")
df

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [7]:
df.head()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,158023,L. Messi,31,https://cdn.sofifa.org/players/4/19/158023.png,Argentina,https://cdn.sofifa.org/flags/52.png,94,94,FC Barcelona,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,20801,Cristiano Ronaldo,33,https://cdn.sofifa.org/players/4/19/20801.png,Portugal,https://cdn.sofifa.org/flags/38.png,94,94,Juventus,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,190871,Neymar Jr,26,https://cdn.sofifa.org/players/4/19/190871.png,Brazil,https://cdn.sofifa.org/flags/54.png,92,93,Paris Saint-Germain,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,193080,De Gea,27,https://cdn.sofifa.org/players/4/19/193080.png,Spain,https://cdn.sofifa.org/flags/45.png,91,93,Manchester United,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,192985,K. De Bruyne,27,https://cdn.sofifa.org/players/4/19/192985.png,Belgium,https://cdn.sofifa.org/flags/7.png,91,92,Manchester City,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M

In [8]:
df.tail()

,Unnamed: 0,ID,Name,Age,Photo,Nationality,Flag,Overall,Potential,Club,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
18202,18202,238813,J. Lundstram,19,https://cdn.sofifa.org/players/4/19/238813.png,England,https://cdn.sofifa.org/flags/14.png,47,65,Crewe Alexandra,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,243165,N. Christoffersson,19,https://cdn.sofifa.org/players/4/19/243165.png,Sweden,https://cdn.sofifa.org/flags/46.png,47,63,Trelleborgs FF,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,241638,B. Worman,16,https://cdn.sofifa.org/players/4/19/241638.png,England,https://cdn.sofifa.org/flags/14.png,47,67,Cambridge United,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,246268,D. Walker-Rice,17,https://cdn.sofifa.org/players/4/19/246268.png,England,https://cdn.sofifa.org/flags/14.png,47,66,Tranmere Rovers,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,246269,G. Nugent,16,https://cdn.sofifa.org/players/4/19/246269.png,England,https://cdn.sofifa.org/flags/14.png,46,66,Tranmere Rovers,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [10]:
df.shape

(18207, 89)

In [17]:
df.drop(columns=['Photo','Flag','Club Logo','ID','Real Face'],inplace=True)

In [18]:
df

,Unnamed: 0,Name,Age,Nationality,Overall,Potential,Club,Value,Wage,Special,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
0,0,L. Messi,31,Argentina,94,94,FC Barcelona,€110.5M,€565K,2202,...,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0,€226.5M
1,1,Cristiano Ronaldo,33,Portugal,94,94,Juventus,€77M,€405K,2228,...,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0,€127.1M
2,2,Neymar Jr,26,Brazil,92,93,Paris Saint-Germain,€118.5M,€290K,2143,...,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0,€228.1M
3,3,De Gea,27,Spain,91,93,Manchester United,€72M,€260K,1471,...,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0,€138.6M
4,4,K. De Bruyne,27,Belgium,91,92,Manchester City,€102M,€355K,2281,...,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0,€196.4M
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,18202,J. Lundstram,19,England,47,65,Crewe Alexandra,€60K,€1K,1307,...,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0,€143K
18203,18203,N. Christoffersson,19,Sweden,47,63,Trelleborgs FF,€60K,€1K,1098,...,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0,€113K
18204,18204,B. Worman,16,England,47,67,Cambridge United,€60K,€1K,1189,...,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0,€165K
18205,18205,D. Walker-Rice,17,England,47,66,Tranmere Rovers,€60K,€1K,1228,...,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0,€143K
18206,18206,G. Nugent,16,England,46,66,Tranmere Rovers,€60K,€1K,1321,...,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0,€165K

In [19]:
df.isnull().sum()

Unnamed: 0           0
Name                 0
Age                  0
Nationality          0
Overall              0
                  ...
GKHandling          48
GKKicking           48
GKPositioning       48
GKReflexes          48
Release Clause    1564
Length: 84, dtype: int64

In [20]:
df.isnull().sum()/len(df)*100

Unnamed: 0        0.000000
Name              0.000000
Age               0.000000
Nationality       0.000000
Overall           0.000000
                    ...
GKHandling        0.263635
GKKicking         0.263635
GKPositioning     0.263635
GKReflexes        0.263635
Release Clause    8.590103
Length: 84, dtype: float64

In [21]:
drop_colls=[col_name for col_name in df.columns if df[col_name].isna().sum()/len(df)*100 >10.0]
print(drop_colls)

['Loaned From', 'LS', 'ST', 'RS', 'LW', 'LF', 'CF', 'RF', 'RW', 'LAM', 'CAM', 'RAM', 'LM', 'LCM', 'CM', 'RCM', 'RM', 'LWB', 'LDM', 'CDM', 'RDM', 'RWB', 'LB', 'LCB', 'CB', 'RCB', 'RB']

KeyError: '[0] not found in axis'

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 18207 entries, 0 to 18206
Data columns (total 57 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Unnamed: 0                18207 non-null  int64
 1   Name                      18207 non-null  object
 2   Age                       18207 non-null  int64
 3   Nationality               18207 non-null  object
 4   Overall                   18207 non-null  int64
 5   Potential                 18207 non-null  int64
 6   Club                      17966 non-null  object
 7   Value                     18207 non-null  object
 8   Wage                      18207 non-null  object
 9   Special                   18207 non-null  int64
 10  Preferred Foot            18159 non-null  object
 11  International Reputation  18159 non-null  float64
 12  Weak Foot                 18159 non-null  float64
 13  Skill Moves               18159 non-null  float64
 14  Work Rate                 18159 non-null  object
 15  Body Type                 18159 non-null  object
 16  Position                  18147 non-null  object
 17  Jersey Number             18147 non-null  float64
 18  Joined                    16654 non-null  object
 19  Contract Valid Until      17918 non-null  object
 20  Height                    18159 non-null  object
 21  Weight                    18159 non-null  object
 22  Crossing                  18159 non-null  float64
 23  Finishing                 18159 non-null  float64
 24  HeadingAccuracy           18159 non-null  float64
 25  ShortPassing              18159 non-null  float64
 26  Volleys                   18159 non-null  float64
 27  Dribbling                 18159 non-null  float64
 28  Curve                     18159 non-null  float64
 29  FKAccuracy                18159 non-null  float64
 30  LongPassing               18159 non-null  float64
 31  BallControl               18159 non-null  float64
 32  Acceleration              18159 non-null  float64
 33  SprintSpeed               18159 non-null  float64
 34  Agility                   18159 non-null  float64
 35  Reactions                 18159 non-null  float64
 36  Balance                   18159 non-null  float64
 37  ShotPower                 18159 non-null  float64
 38  Jumping                   18159 non-null  float64
 39  Stamina                   18159 non-null  float64
 40  Strength                  18159 non-null  float64
 41  LongShots                 18159 non-null  float64
 42  Aggression                18159 non-null  float64
 43  Interceptions             18159 non-null  float64
 44  Positioning               18159 non-null  float64
 45  Vision                    18159 non-null  float64
 46  Penalties                 18159 non-null  float64
 47  Composure                 18159 non-null  float64
 48  Marking                   18159 non-null  float64
 49  StandingTackle            18159 non-null  float64
 50  SlidingTackle             18159 non-null  float64
 51  GKDiving                  18159 non-null  float64
 52  GKHandling                18159 non-null  float64
 53  GKKicking                 18159 non-null  float64
 54  GKPositioning             18159 non-null  float64
 55  GKReflexes                18159 non-null  float64
 56  Release Clause            16643 non-null  object
dtypes: float64(38), int64(5), object(14)
memory usage: 7.9+ MB

In [33]:
def strtofloat(x):
    try:
        if x[-1]=='M':
            return float(x[1:-1])*1000000
        else:
            return float(x[1:-1])*1000
    except:
        return np.nan

In [34]:
df["Release Clause"]=df["Release Clause"].apply(strtofloat)
df['Release Clause']

0        226500000.0
1        127100000.0
2        228100000.0
3        138600000.0
4        196400000.0
            ...
18202       143000.0
18203       113000.0
18204       165000.0
18205       143000.0
18206       165000.0
Name: Release Clause, Length: 18207, dtype: float64

In [37]:
extract=["Crossing","Finishing","HeadingAccuracy","ShortPassing","Volleys","Dribbling","Curve","FKAccuracy","LongPassing","BallControl","Acceleration","SprintSpeed","Agility","Reactions","Balance","ShotPower","Jumping","Stamina","Strength","LongShots","Aggression","Interceptions","Positioning","Vision","Penalties","Composure","Marking","StandingTackle","SlidingTackle","GKDiving","GKHandling","GKKicking","GKPositioning","GKReflexes"]
df1=df[extract]

In [38]:
df1

,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,84.0,95.0,70.0,90.0,86.0,97.0,93.0,94.0,87.0,96.0,...,75.0,96.0,33.0,28.0,26.0,6.0,11.0,15.0,14.0,8.0
1,84.0,94.0,89.0,81.0,87.0,88.0,81.0,76.0,77.0,94.0,...,85.0,95.0,28.0,31.0,23.0,7.0,11.0,15.0,14.0,11.0
2,79.0,87.0,62.0,84.0,84.0,96.0,88.0,87.0,78.0,95.0,...,81.0,94.0,27.0,24.0,33.0,9.0,9.0,15.0,15.0,11.0
3,17.0,13.0,21.0,50.0,13.0,18.0,21.0,19.0,51.0,42.0,...,40.0,68.0,15.0,21.0,13.0,90.0,85.0,87.0,88.0,94.0
4,93.0,82.0,55.0,92.0,82.0,86.0,85.0,83.0,91.0,91.0,...,79.0,88.0,68.0,58.0,51.0,15.0,13.0,5.0,10.0,13.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18202,34.0,38.0,40.0,49.0,25.0,42.0,30.0,34.0,45.0,43.0,...,43.0,45.0,40.0,48.0,47.0,10.0,13.0,7.0,8.0,9.0
18203,23.0,52.0,52.0,43.0,36.0,39.0,32.0,20.0,25.0,40.0,...,43.0,42.0,22.0,15.0,19.0,10.0,9.0,9.0,5.0,12.0
18204,25.0,40.0,46.0,38.0,38.0,45.0,38.0,27.0,28.0,44.0,...,55.0,41.0,32.0,13.0,11.0,6.0,5.0,10.0,6.0,13.0
18205,44.0,50.0,39.0,42.0,40.0,51.0,34.0,32.0,32.0,52.0,...,50.0,46.0,20.0,25.0,27.0,14.0,6.0,14.0,8.0,9.0
18206,41.0,34.0,46.0,48.0,30.0,43.0,40.0,34.0,44.0,51.0,...,33.0,43.0,40.0,43.0,50.0,10.0,15.0,9.0,12.0,9.0

In [39]:
df1.describe()

,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,Curve,FKAccuracy,LongPassing,BallControl,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,...,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000,18159.000000
mean,49.734181,45.550911,52.298144,58.686712,42.909026,55.371001,47.170824,42.863153,52.711933,58.369459,...,48.548598,58.648274,47.281623,47.697836,45.661435,16.616223,16.391596,16.232061,16.388898,16.710887
std,18.364524,19.525820,17.379909,14.699495,17.694408,18.910371,18.395264,17.478763,15.327870,16.686595,...,15.704053,11.436133,19.904397,21.664004,21.289135,17.695349,16.906900,16.502864,17.034669,17.955119
min,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,6.000000,3.000000,9.000000,5.000000,...,5.000000,3.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,38.000000,30.000000,44.000000,54.000000,30.000000,49.000000,34.000000,31.000000,43.000000,54.000000,...,39.000000,51.000000,30.000000,27.000000,24.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,54.000000,49.000000,56.000000,62.000000,44.000000,61.000000,48.000000,41.000000,56.000000,63.000000,...,49.000000,60.000000,53.000000,55.000000,52.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,64.000000,62.000000,64.000000,68.000000,57.000000,68.000000,62.000000,57.000000,64.000000,69.000000,...,60.000000,67.000000,64.000000,66.000000,64.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,94.000000,94.000000,93.000000,96.000000,...,92.000000,96.000000,94.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [40]:
for col in df1.columns:
    df1[col]=df1[col].fillna(df1[col].median())

C:\Users\Kanika\AppData\Local\Temp\ipykernel_9764\4294846630.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df1[col]=df1[col].fillna(df1[col].median())

In [43]:
df1.isnull().sum()

Crossing           0
Finishing          0
HeadingAccuracy    0
ShortPassing       0
Volleys            0
Dribbling          0
Curve              0
FKAccuracy         0
LongPassing        0
BallControl        0
Acceleration       0
SprintSpeed        0
Agility            0
Reactions          0
Balance            0
ShotPower          0
Jumping            0
Stamina            0
Strength           0
LongShots          0
Aggression         0
Interceptions      0
Positioning        0
Vision             0
Penalties          0
Composure          0
Marking            0
StandingTackle     0
SlidingTackle      0
GKDiving           0
GKHandling         0
GKKicking          0
GKPositioning      0
GKReflexes         0
dtype: int64

In [44]:
f=df.groupby("Nationality")

In [45]:
f

In [46]:
f.first()

,Unnamed: 0,Name,Age,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
Nationality,,,,,,,,,,,,,,,,,,,,,
Afghanistan,12891,H. Amin,26,63,64,SV Meppen,€350K,€1K,1592,Left,...,55.0,62.0,54.0,59.0,13.0,7.0,7.0,12.0,14.0,534000.0
Albania,338,T. Strakosha,23,81,86,Lazio,€17M,€36K,1139,Right,...,61.0,20.0,18.0,12.0,81.0,77.0,75.0,78.0,86.0,30200000.0
Algeria,84,R. Mahrez,27,85,85,Manchester City,€40.5M,€205K,2031,Left,...,86.0,45.0,31.0,18.0,15.0,9.0,13.0,11.0,6.0,74900000.0
Andorra,13651,Marc Vales,28,62,64,Sandefjord Fotball,€290K,€1K,1517,Right,...,50.0,54.0,56.0,67.0,9.0,7.0,12.0,8.0,6.0,384000.0
Angola,773,Bastos,26,78,79,Lazio,€10M,€44K,1710,Right,...,67.0,80.0,80.0,77.0,13.0,8.0,11.0,12.0,12.0,17800000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,1712,O. Akhmedov,30,75,75,Shanghai SIPG FC,€6M,€17K,2018,Right,...,69.0,73.0,72.0,69.0,11.0,12.0,16.0,12.0,14.0,13200000.0
Venezuela,345,J. Martínez,25,81,84,Atlanta United,€22.5M,€14K,1917,Right,...,75.0,20.0,20.0,15.0,12.0,14.0,14.0,12.0,8.0,35400000.0
Wales,36,G. Bale,28,88,88,Real Madrid,€60M,€355K,2279,Left,...,86.0,54.0,55.0,52.0,15.0,15.0,11.0,5.0,6.0,123000000.0
Zambia,2757,S. Sunzu,29,73,74,FC Metz,€3.5M,€7K,1687,Right,...,67.0,71.0,74.0,72.0,14.0,15.0,12.0,9.0,10.0,6600000.0
Zimbabwe,764,M. Nakamba,24,78,83,Club Brugge KV,€12M,€20K,1937,Left,...,71.0,80.0,80.0,78.0,9.0,15.0,10.0,15.0,8.0,18900000.0

In [52]:
f.index=[10,20,30]
f.first()

,Unnamed: 0,Name,Age,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
Nationality,,,,,,,,,,,,,,,,,,,,,
Afghanistan,12891,H. Amin,26,63,64,SV Meppen,€350K,€1K,1592,Left,...,55.0,62.0,54.0,59.0,13.0,7.0,7.0,12.0,14.0,534000.0
Albania,338,T. Strakosha,23,81,86,Lazio,€17M,€36K,1139,Right,...,61.0,20.0,18.0,12.0,81.0,77.0,75.0,78.0,86.0,30200000.0
Algeria,84,R. Mahrez,27,85,85,Manchester City,€40.5M,€205K,2031,Left,...,86.0,45.0,31.0,18.0,15.0,9.0,13.0,11.0,6.0,74900000.0
Andorra,13651,Marc Vales,28,62,64,Sandefjord Fotball,€290K,€1K,1517,Right,...,50.0,54.0,56.0,67.0,9.0,7.0,12.0,8.0,6.0,384000.0
Angola,773,Bastos,26,78,79,Lazio,€10M,€44K,1710,Right,...,67.0,80.0,80.0,77.0,13.0,8.0,11.0,12.0,12.0,17800000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,1712,O. Akhmedov,30,75,75,Shanghai SIPG FC,€6M,€17K,2018,Right,...,69.0,73.0,72.0,69.0,11.0,12.0,16.0,12.0,14.0,13200000.0
Venezuela,345,J. Martínez,25,81,84,Atlanta United,€22.5M,€14K,1917,Right,...,75.0,20.0,20.0,15.0,12.0,14.0,14.0,12.0,8.0,35400000.0
Wales,36,G. Bale,28,88,88,Real Madrid,€60M,€355K,2279,Left,...,86.0,54.0,55.0,52.0,15.0,15.0,11.0,5.0,6.0,123000000.0
Zambia,2757,S. Sunzu,29,73,74,FC Metz,€3.5M,€7K,1687,Right,...,67.0,71.0,74.0,72.0,14.0,15.0,12.0,9.0,10.0,6600000.0
Zimbabwe,764,M. Nakamba,24,78,83,Club Brugge KV,€12M,€20K,1937,Left,...,71.0,80.0,80.0,78.0,9.0,15.0,10.0,15.0,8.0,18900000.0

In [48]:
f

In [49]:
f.first()

,Unnamed: 0,Name,Age,Overall,Potential,Club,Value,Wage,Special,Preferred Foot,...,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes,Release Clause
Nationality,,,,,,,,,,,,,,,,,,,,,
Afghanistan,12891,H. Amin,26,63,64,SV Meppen,€350K,€1K,1592,Left,...,55.0,62.0,54.0,59.0,13.0,7.0,7.0,12.0,14.0,534000.0
Albania,338,T. Strakosha,23,81,86,Lazio,€17M,€36K,1139,Right,...,61.0,20.0,18.0,12.0,81.0,77.0,75.0,78.0,86.0,30200000.0
Algeria,84,R. Mahrez,27,85,85,Manchester City,€40.5M,€205K,2031,Left,...,86.0,45.0,31.0,18.0,15.0,9.0,13.0,11.0,6.0,74900000.0
Andorra,13651,Marc Vales,28,62,64,Sandefjord Fotball,€290K,€1K,1517,Right,...,50.0,54.0,56.0,67.0,9.0,7.0,12.0,8.0,6.0,384000.0
Angola,773,Bastos,26,78,79,Lazio,€10M,€44K,1710,Right,...,67.0,80.0,80.0,77.0,13.0,8.0,11.0,12.0,12.0,17800000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Uzbekistan,1712,O. Akhmedov,30,75,75,Shanghai SIPG FC,€6M,€17K,2018,Right,...,69.0,73.0,72.0,69.0,11.0,12.0,16.0,12.0,14.0,13200000.0
Venezuela,345,J. Martínez,25,81,84,Atlanta United,€22.5M,€14K,1917,Right,...,75.0,20.0,20.0,15.0,12.0,14.0,14.0,12.0,8.0,35400000.0
Wales,36,G. Bale,28,88,88,Real Madrid,€60M,€355K,2279,Left,...,86.0,54.0,55.0,52.0,15.0,15.0,11.0,5.0,6.0,123000000.0
Zambia,2757,S. Sunzu,29,73,74,FC Metz,€3.5M,€7K,1687,Right,...,67.0,71.0,74.0,72.0,14.0,15.0,12.0,9.0,10.0,6600000.0
Zimbabwe,764,M. Nakamba,24,78,83,Club Brugge KV,€12M,€20K,1937,Left,...,71.0,80.0,80.0,78.0,9.0,15.0,10.0,15.0,8.0,18900000.0